POST http://localhost:8000/consumption-tariff/end-episode
Content-Type: application/json

{
  "episode_id": "{{episode_id}}",
  "observation": {
    "timeslot": 360,
    "gameId": "PowerTAC GameId",
    "gridImbalance": 12300.0,
    "ownImbalanceKwh": 22.0,
    "consumptionShare": 0.2,
    "productionShare": 0.4,
    "customerNetDemand": 1.4,
    "wholesalePrice": 0.51,
    "ownWholesalePrice": 0.3,
    "cashPosition": 1200.41,
    "marketPosition": 0
  }
}

###
